#!/bin/bash

: '
Author: Alexander Zsikla
setup

This is a basic script that downloads/updates the following items:
- brew
- python3
- mechwolf (python library)
- jupyter (python library)

As well as adds in an alias into ones .bashrc file that allows them
to open up the github repo automatically
'

RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
NC="\033[0m"

install () {
    echo -e "\n$2$1$NC $3"

    if [ ! -z "$4" ]; then
        echo "$4"
    fi

    sleep 2
}

# Installing homebrew
if ! command -v brew &> /dev/null; then
    install "ERROR" $RED "Homebrew is not installed on this computer" "Installing Homebrew"
    echo -e "This may take a couple of minutes depending on internet connection\n"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew update

# Installing python3
if ! command -v python3 || ! command brew search python3 &> /dev/null; then
    install "ERROR" $RED "Python3 is not installed on this computer" "Installing Python3" 
    brew install python3
    brew link python3
else 
    install "NOTE" $YELLOW "Python3 is installed"

    brew upgrade python3
fi

# Updating pip3 if needed
install "Pip3" $YELLOW "Updating pip3 if needed"

$(which python3) -m pip install --upgrade pip

# Installing mechwolf
install "Mechwolf" $GREEN "Installing mechwolf"

if [ ! -f requirements.txt ]; then
    install "ERROR" $RED "requirements.txt not found" \
        "Make sure you are running this script from inside the flow-synthesis directory"
    exit 1
fi

pip3 install -r requirements.txt

case $(grep "alias wolf*" ~/.bashrc > /dev/null; echo $?) in
  0)
    install "Warning" $YELLOW 'Alias already found in ~/.bashrc'
    ;;
  1)
    install "Alias" $GREEN "Putting an alias in ~/.bashrc for convenience"
    echo -e "\nalias wolf='cd ~/Desktop/flow-synthesis; jupyter notebook'" >> ~/.bashrc
    ;;
  *)
    install "ERROR" $RED "Issue with grep'ing for alias"
    exit 2
    ;;
esac

source ~/.bashrc
